-- Create a table
CREATE TABLE ExchangeRate (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EXCHANGE_RATE_AMOUNT DECIMAL(10, 2),
    CURRENCY_SOURCE VARCHAR(3),
    CURRENCY_TARGET VARCHAR(3)
);

-- Insert data
INSERT INTO ExchangeRate (EXCHANGE_RATE_AMOUNT, CURRENCY_SOURCE, CURRENCY_TARGET) VALUES (0.5, 'PEN', 'USD');
INSERT INTO ExchangeRate (EXCHANGE_RATE_AMOUNT, CURRENCY_SOURCE, CURRENCY_TARGET) VALUES (3.2, 'USD', 'PEN');